"""
SISCA — Setup Oracle XE 21c (PDB compatible)
Detecta CDB/PDB y crea el esquema en el contenedor correcto
Ejecutar: python setup_oracle.py
"""
import os, sys
from dotenv import load_dotenv
load_dotenv()

import oracledb
import bcrypt

HOST    = os.getenv('ORACLE_HOST', 'localhost')
PORT    = os.getenv('ORACLE_PORT', '1521')
SYS_PWD = os.getenv('ORACLE_SYSTEM_PASSWORD', 'fjnv1305')
APP_USR = 'sisca_admin'
APP_PWD = os.getenv('ORACLE_PASSWORD', 'fjnv1305')

def bar(): print('-' * 55)
def ok(msg): print(f'  [OK] {msg}')
def err(msg): print(f'  [!!] {msg}')
def info(msg): print(f'       {msg}')

print('=' * 55)
print('  SISCA — Setup Oracle XE 21c')
print('=' * 55)

# ── 1. Detectar DSN de SYSTEM ────────────────────────────────
# En Oracle 21c XE: CDB=XE, PDB=XEPDB1
print('\n[1/6] Detectando DSN...')
dsn_system = f"{HOST}:{PORT}/XE"          # CDB root
dsn_pdb    = f"{HOST}:{PORT}/XEPDB1"      # PDB (donde van usuarios en 21c)

print(f'  Oracle 21c XE detectado: usando PDB XEPDB1')
ok(f'DSN SYSTEM (CDB): {dsn_system}')
ok(f'DSN App   (PDB): {dsn_pdb}')

# ── 2. Conectar como SYSDBA al CDB para crear usuario ────────
bar()
print('[2/6] Conectando como SYSDBA para crear usuario...')
try:
    # En Oracle 21c XE conectar al CDB root como SYSDBA
    conn_sys = oracledb.connect(
        user='SYS', password=SYS_PWD,
        dsn=dsn_system,
        mode=oracledb.AUTH_MODE_SYSDBA
    )
    cur_sys = conn_sys.cursor()

    # Verificar versión
    cur_sys.execute("SELECT * FROM v$version WHERE ROWNUM=1")
    ver = cur_sys.fetchone()
    ok(f'Oracle: {ver[0][:55] if ver else "OK"}')
except Exception as e1:
    err(f'SYS SYSDBA falló: {e1}')
    print('  Intentando con SYSTEM...')
    try:
        conn_sys = oracledb.connect(user='SYSTEM', password=SYS_PWD, dsn=dsn_system)
        cur_sys  = conn_sys.cursor()
        ok('Conectado como SYSTEM al CDB')
    except Exception as e2:
        err(f'Falló: {e2}')
        sys.exit(1)

# ── 3. Crear usuario en el PDB (XEPDB1) ─────────────────────
bar()
print('[3/6] Creando usuario sisca_admin en PDB XEPDB1...')

# Primero alternar al PDB
try:
    cur_sys.execute("ALTER SESSION SET CONTAINER = XEPDB1")
    ok('Sesion alterada a XEPDB1')
except Exception as e:
    err(f'No se pudo cambiar a XEPDB1: {e}')
    info('Intentando con usuario comun C##sisca_admin...')
    APP_USR = 'C##sisca_admin'

# Verificar si el usuario ya existe
try:
    cur_sys.execute("SELECT COUNT(*) FROM dba_users WHERE username = UPPER(:u)", {'u': APP_USR})
    exists = cur_sys.fetchone()[0]
    if exists:
        ok(f'Usuario {APP_USR} ya existe. Eliminando...')
        cur_sys.execute(f'DROP USER {APP_USR} CASCADE')
        conn_sys.commit()
        ok('Usuario anterior eliminado.')
except Exception as e:
    info(f'Check usuario: {e}')

# Crear usuario
try:
    cur_sys.execute(f"""
        CREATE USER {APP_USR} IDENTIFIED BY "{APP_PWD}"
        DEFAULT TABLESPACE USERS
        TEMPORARY TABLESPACE TEMP
        QUOTA UNLIMITED ON USERS
    """)
    conn_sys.commit()
    cur_sys.execute(f"GRANT CONNECT, RESOURCE TO {APP_USR}")
    cur_sys.execute(f"GRANT CREATE SESSION TO {APP_USR}")
    cur_sys.execute(f"GRANT CREATE TABLE TO {APP_USR}")
    cur_sys.execute(f"GRANT CREATE SEQUENCE TO {APP_USR}")
    cur_sys.execute(f"GRANT CREATE VIEW TO {APP_USR}")
    cur_sys.execute(f"GRANT UNLIMITED TABLESPACE TO {APP_USR}")
    conn_sys.commit()
    ok(f'Usuario {APP_USR} creado con todos los permisos')
except Exception as e:
    err(f'Error creando usuario: {e}')
    conn_sys.rollback()
    sys.exit(1)

conn_sys.close()

# ── 4. Conectar como sisca_admin al PDB ─────────────────────
bar()
print('[4/6] Conectando como sisca_admin al PDB XEPDB1...')
try:
    conn = oracledb.connect(user=APP_USR, password=APP_PWD, dsn=dsn_pdb)
    cur  = conn.cursor()
    ok(f'Conectado: {APP_USR} @ {dsn_pdb}')
except Exception as e:
    err(f'Error: {e}')
    sys.exit(1)

# ── 5. Crear tablas ──────────────────────────────────────────
bar()
print('[5/6] Creando tablas SISCA...')

TABLAS = {
    'USUARIO': """CREATE TABLE USUARIO (
        ID_USUARIO       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ESTADO           CHAR(1)       DEFAULT 'A' NOT NULL,
        NOMBRE           VARCHAR2(100) NOT NULL,
        APELLIDO         VARCHAR2(100) NOT NULL,
        CORREO           VARCHAR2(120) NOT NULL,
        CONTRASENA       VARCHAR2(255) NOT NULL,
        ROL              VARCHAR2(20)  NOT NULL,
        ACEPTA_TERMINOS  CHAR(1)       DEFAULT 'N',
        FECHA_REGISTRO   TIMESTAMP     DEFAULT SYSTIMESTAMP,
        CONSTRAINT uq_usr_correo UNIQUE (CORREO),
        CONSTRAINT ck_usr_rol    CHECK (ROL IN ('ADMINISTRADOR','DOCENTE','ESTUDIANTE')),
        CONSTRAINT ck_usr_estado CHECK (ESTADO IN ('A','I')))""",
    'ADMINISTRADOR': """CREATE TABLE ADMINISTRADOR (
        ID_ADMINISTRADOR NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_USUARIO       NUMBER NOT NULL,
        NIVEL_ACCESO     VARCHAR2(10) DEFAULT 'TOTAL',
        CONSTRAINT fk_adm_usr FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO))""",
    'DOCENTE': """CREATE TABLE DOCENTE (
        ID_DOCENTE   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_USUARIO   NUMBER NOT NULL,
        ESPECIALIDAD VARCHAR2(100),
        TELEFONO     VARCHAR2(20),
        CONSTRAINT fk_doc_usr FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO))""",
    'ESTUDIANTE': """CREATE TABLE ESTUDIANTE (
        ID_ESTUDIANTE     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_USUARIO        NUMBER NOT NULL,
        SEMESTRE          NUMBER(2),
        CODIGO_ESTUDIANTE NUMBER,
        CONSTRAINT fk_est_usr  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
        CONSTRAINT uq_cod_est  UNIQUE (CODIGO_ESTUDIANTE))""",
    'CARRERA': """CREATE TABLE CARRERA (
        ID_CARRERA     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOMBRE_CARRERA VARCHAR2(100) NOT NULL,
        FACULTAD       VARCHAR2(100),
        CODIGO_CARRERA VARCHAR2(20),
        ESTADO         CHAR(1) DEFAULT 'A')""",
    'MATERIA': """CREATE TABLE MATERIA (
        ID_MATERIA     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_CARRERA     NUMBER,
        ID_DOCENTE     NUMBER,
        NOMBRE_MATERIA VARCHAR2(150) NOT NULL,
        CODIGO         VARCHAR2(20),
        CREDITOS       NUMBER(2),
        SEMESTRE       NUMBER(2),
        PORCENTAJE_MIN NUMBER(5,2) DEFAULT 75.00,
        ESTADO         CHAR(1) DEFAULT 'A',
        CONSTRAINT fk_mat_car FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA(ID_CARRERA),
        CONSTRAINT fk_mat_doc FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE))""",
    'HORARIO': """CREATE TABLE HORARIO (
        ID_HORARIO  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_MATERIA  NUMBER NOT NULL,
        HORA_INICIO TIMESTAMP NOT NULL,
        HORA_FIN    TIMESTAMP NOT NULL,
        DIA         VARCHAR2(20) NOT NULL,
        AULA        VARCHAR2(30),
        ESTADO      CHAR(1) DEFAULT 'A',
        CONSTRAINT fk_hor_mat FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA))""",
    'INSCRIPCION': """CREATE TABLE INSCRIPCION (
        ID_INSCRIPCION    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_ESTUDIANTE     NUMBER NOT NULL,
        ID_MATERIA        NUMBER NOT NULL,
        FECHA_INSCRIPCION DATE DEFAULT SYSDATE,
        SEMESTRE          NUMBER(2),
        ESTADO            VARCHAR2(20) DEFAULT 'ACTIVA',
        CONSTRAINT fk_ins_est FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
        CONSTRAINT fk_ins_mat FOREIGN KEY (ID_MATERIA)    REFERENCES MATERIA(ID_MATERIA),
        CONSTRAINT ck_ins_est CHECK (ESTADO IN ('ACTIVA','CANCELADA','COMPLETADA')))""",
    'SESION_CLASE': """CREATE TABLE SESION_CLASE (
        ID_SESION     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_HORARIO    NUMBER NOT NULL,
        FECHA_SESION  DATE DEFAULT SYSDATE,
        ESTADO_SESION VARCHAR2(30) DEFAULT 'ACTIVA',
        MODO_CONEXION VARCHAR2(20) DEFAULT 'ONLINE',
        CONSTRAINT fk_ses_hor FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO),
        CONSTRAINT ck_ses_est CHECK (ESTADO_SESION IN ('ACTIVA','CERRADA','CANCELADA')),
        CONSTRAINT ck_ses_mod CHECK (MODO_CONEXION IN ('ONLINE','OFFLINE')))""",
    'CODIGO_QR': """CREATE TABLE CODIGO_QR (
        ID_QR            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_SESION        NUMBER NOT NULL,
        FECHA_GENERACION TIMESTAMP DEFAULT SYSTIMESTAMP,
        FECHA_EXPIRACION TIMESTAMP NOT NULL,
        CODIGO           VARCHAR2(250) NOT NULL,
        IP_LOCAL         VARCHAR2(50),
        USADO            CHAR(1) DEFAULT 'N',
        CONSTRAINT fk_qr_ses FOREIGN KEY (ID_SESION) REFERENCES SESION_CLASE(ID_SESION),
        CONSTRAINT uq_qr_cod UNIQUE (CODIGO))""",
    'ASISTENCIA': """CREATE TABLE ASISTENCIA (
        ID_ASISTENCIA  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_SESION      NUMBER NOT NULL,
        ID_ESTUDIANTE  NUMBER NOT NULL,
        FECHA          DATE DEFAULT SYSDATE,
        HORA_REGISTRO  TIMESTAMP DEFAULT SYSTIMESTAMP,
        ESTADO         VARCHAR2(20) DEFAULT 'PRESENTE',
        TIPO_REGISTRO  VARCHAR2(20) DEFAULT 'QR',
        ID_DISPOSITIVO VARCHAR2(100),
        LATITUD        NUMBER(10,7),
        LONGITUD       NUMBER(10,7),
        CONSTRAINT fk_asi_ses FOREIGN KEY (ID_SESION)    REFERENCES SESION_CLASE(ID_SESION),
        CONSTRAINT fk_asi_est FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
        CONSTRAINT uq_asist   UNIQUE (ID_SESION, ID_ESTUDIANTE),
        CONSTRAINT ck_asi_est CHECK (ESTADO IN ('PRESENTE','AUSENTE','JUSTIFICADO')),
        CONSTRAINT ck_asi_tip CHECK (TIPO_REGISTRO IN ('QR','MANUAL','ENLACE','OFFLINE')))""",
    'JUSTIFICACION': """CREATE TABLE JUSTIFICACION (
        ID_JUSTIFICACION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_ASISTENCIA    NUMBER,
        ID_DOCENTE       NUMBER,
        MOTIVO           VARCHAR2(500),
        FECHA_REGISTRO   TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_jus_asi FOREIGN KEY (ID_ASISTENCIA) REFERENCES ASISTENCIA(ID_ASISTENCIA),
        CONSTRAINT fk_jus_doc FOREIGN KEY (ID_DOCENTE)    REFERENCES DOCENTE(ID_DOCENTE))""",
    'AUDITORIA': """CREATE TABLE AUDITORIA (
        ID_LOG         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_USUARIO     NUMBER,
        FECHA          TIMESTAMP DEFAULT SYSTIMESTAMP,
        ACCION         VARCHAR2(150) NOT NULL,
        TABLA_AFECTADA VARCHAR2(50),
        IP             VARCHAR2(50),
        CONSTRAINT fk_aud_usr FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO))""",
    'SERVIDOR_LOCAL': """CREATE TABLE SERVIDOR_LOCAL (
        ID_SERVIDOR_LOCAL NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        IP_LOCAL          VARCHAR2(50),
        ESTADO_SERVIDOR   VARCHAR2(20) DEFAULT 'ACTIVO')""",
    'SINCRONIZACION': """CREATE TABLE SINCRONIZACION (
        ID_SINCRONIZACION    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_SERVIDOR          NUMBER,
        FECHA_SINCRONIZACION TIMESTAMP DEFAULT SYSTIMESTAMP,
        ESTADO_CONEXION      VARCHAR2(30),
        REGISTROS_SYNC       NUMBER DEFAULT 0,
        CONSTRAINT fk_sin_srv FOREIGN KEY (ID_SERVIDOR) REFERENCES SERVIDOR_LOCAL(ID_SERVIDOR_LOCAL))""",
    'ALERTA_INASISTENCIA': """CREATE TABLE ALERTA_INASISTENCIA (
        ID_ALERTA         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ID_ESTUDIANTE     NUMBER,
        ID_MATERIA        NUMBER,
        PORCENTAJE_ACTUAL NUMBER(5,2),
        NOTIFICADO        CHAR(1) DEFAULT 'N',
        FECHA_ALERTA      TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_ale_est FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
        CONSTRAINT fk_ale_mat FOREIGN KEY (ID_MATERIA)    REFERENCES MATERIA(ID_MATERIA))""",
}

creadas = 0
for nombre, ddl in TABLAS.items():
    try:
        cur.execute(ddl)
        conn.commit()
        ok(f'Tabla {nombre}')
        creadas += 1
    except Exception as e:
        info(f'Tabla {nombre}: {e}')

print(f'\n  Tablas creadas: {creadas}/{len(TABLAS)}')

# Índices
for idx_sql in [
    "CREATE INDEX IDX_ASIST_EST  ON ASISTENCIA(ID_ESTUDIANTE)",
    "CREATE INDEX IDX_ASIST_SES  ON ASISTENCIA(ID_SESION)",
    "CREATE INDEX IDX_ASIST_FEC  ON ASISTENCIA(FECHA)",
    "CREATE INDEX IDX_LOG_FEC    ON AUDITORIA(FECHA)",
    "CREATE INDEX IDX_QR_COD     ON CODIGO_QR(CODIGO)",
    "CREATE INDEX IDX_SES_HOR    ON SESION_CLASE(ID_HORARIO)",
    "CREATE INDEX IDX_MAT_CAR    ON MATERIA(ID_CARRERA)",
    "CREATE INDEX IDX_USR_COR    ON USUARIO(CORREO)",
]:
    try:
        cur.execute(idx_sql)
        conn.commit()
    except Exception:
        pass

# ── 6. Datos iniciales ───────────────────────────────────────
bar()
print('[6/6] Insertando datos iniciales...')

pwd_hash = bcrypt.hashpw('Admin2026!'.encode(), bcrypt.gensalt()).decode()

try:
    cur.execute("""
        INSERT INTO USUARIO(ESTADO,NOMBRE,APELLIDO,CORREO,CONTRASENA,ROL,ACEPTA_TERMINOS)
        VALUES('A','Administrador','SISCA','admin@politecnico.edu.co',:pwd,'ADMINISTRADOR','S')
    """, {'pwd': pwd_hash})
    conn.commit()

    cur.execute("SELECT ID_USUARIO FROM USUARIO WHERE CORREO='admin@politecnico.edu.co'")
    aid = cur.fetchone()[0]
    cur.execute("INSERT INTO ADMINISTRADOR(ID_USUARIO,NIVEL_ACCESO) VALUES(:id,'TOTAL')", {'id': aid})
    conn.commit()
    ok(f'Admin: admin@politecnico.edu.co / Admin2026! (ID:{aid})')

    # Carrera de ejemplo
    cur.execute("""
        INSERT INTO CARRERA(NOMBRE_CARRERA,FACULTAD,CODIGO_CARRERA)
        VALUES('Ingenieria de Sistemas','Ingenieria','ING-SIS')
    """)
    conn.commit()
    ok('Carrera ejemplo: Ingenieria de Sistemas')

except Exception as e:
    err(f'Datos iniciales: {e}')
    conn.rollback()

conn.close()

# ── Actualizar .env con DSN correcto para PDB ───────────────
bar()
env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')
with open(env_path, 'r', encoding='utf-8') as f:
    content = f.read()

import re
# Reemplazo por línea completa (no substring) para que sea idempotente:
# volver a correr el script no debe ir concatenando "PDB1" cada vez.
content = re.sub(r'^ORACLE_SID=.*$', 'ORACLE_SID=XEPDB1', content, flags=re.MULTILINE)
content = re.sub(r'^ORACLE_USER=.*$', f'ORACLE_USER={APP_USR}', content, flags=re.MULTILINE)

with open(env_path, 'w', encoding='utf-8') as f:
    f.write(content)

ok(f'.env actualizado: ORACLE_SID=XEPDB1, ORACLE_USER={APP_USR}')

print('\n' + '=' * 55)
print('  SETUP COMPLETADO')
print('=' * 55)
print(f'  Usuario  : {APP_USR} @ {dsn_pdb}')
print(f'  Tablas   : {creadas}/17')
print(f'  Admin    : admin@politecnico.edu.co')
print(f'  Password : Admin2026!')
print(f'\n  Inicia el servidor:')
print(f'  python run.py')
print('=' * 55)
